version: "3.8"
services:
  db:
    build: ./database
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
  app:
    build: .
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_USER: $MYSQL_ROOT_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_HOST: db
    ports:
      - $PORT:$PORT
    depends_on:
      - db
    restart: on-failure
volumes:
  dbdata:
